### ISSUE TITLE
HTML formatting doesn't work in Incoming Webhook source

### ISSUE THREAD

**Issue by Aliaksandr-K-JazzTeam** [notify-events/notify-events#2]
I tried to send text with `<br>` and `<b>` tags, but on Skype, Telegram and Email I receive notifications without formatting. If I place to text `\n` then it will be replaced with simple space character

**Comment by papajojo** [comment]
Hello, @Aliaksandr-Kasko-JazzTeam! Please try again, should be fixed now.
