### ISSUE TITLE
Filters are not working

### ISSUE THREAD

**Issue by defoxed** [notify-events/notify-events#4]
I noticed that the filters (priority/level) were not working recently. For example when a message with Pririty:Low and Level:Notice is received (in my case from Home Assistant) it is sent to all the recipients regardless of their filters. In the message list priority and level are displayed correctly.

**Comment by matrozov** [comment]
Yes, our team is already handling this problem, thanks for the report!

**Comment by papajojo** [comment]
Hello, @defoxed! Now filters should work correctly. Thanks again for the report!
