### ISSUE TITLE
Threema support?

### ISSUE THREAD

**Issue by timmrogers** [notify-events/notify-events#5]
I just wondered if you might be willing and able to add support for Threema. We are migrating to Threema.Work, and I'd like to be able to send notifications to it rather than SMS.

My guess is that this would be doable. Threema offers a nice API.

https://gateway.threema.ch/en/developer/api

Thank you for considering this!

**Comment by papajojo** [comment]
Hello, @timmrogers!

Yes, you are right, the integration does not look technically difficult. There is only one point: we will be able to provide the Threema notification only through "Notify.Events integrations", where we will ask you to specify your Threema ID (all your subscribers will get messages from) and Secret, with billing on the Threema's side.

We could release this integration in the next 1-2 weeks if you could help us with testing it.

If you are ready to help us with this, please email us at support@notify.events to discuss the details!
